-- mv usefull commands --

-- drop mv on particular table --
drop materialized view on h_lineitem;
drop materialized view on h_customer;
drop materialized view on h_order;
drop materialized view on h_supplier;
drop materialized view on h_nation;
drop materialized view on h_region;

-- drop particular mv --
drop materialized view h_lineitem;
drop materialized view h_customer;
drop materialized view h_order;
drop materialized view h_supplier;
drop materialized view h_nation;
drop materialized view h_region;

-- display mv log content --
select * from PRICING_SUMMARY_REPORT;
select * from LOCAL_SUPPLIER_VOLUME;
select * from FORECASTING_REVENUE_CHANGE;
select * from RETURNED_ITEM_REPORTING;
select * from SHIPPING_MOD_AND_ORDER_PRIO;
select * from SHIPPING_PRIORITY;

-- mvs logs info table -- 
select * from user_mviews where OWNER='TPCH';

-- set refresh mode --
ALTER MATERIALIZED VIEW FORECASTING_REVENUE_CHANGE REFRESH ON COMMIT;
ALTER MATERIALIZED VIEW LOCAL_SUPPLIER_VOLUME REFRESH ON COMMIT;
ALTER MATERIALIZED VIEW PRICING_SUMMARY_REPORT REFRESH ON COMMIT;
ALTER MATERIALIZED VIEW RETURNED_ITEM_REPORTING REFRESH ON COMMIT;
ALTER MATERIALIZED VIEW SHIPPING_MOD_AND_ORDER_PRIO REFRESH ON COMMIT;
ALTER MATERIALIZED VIEW SHIPPING_PRIORITY REFRESH ON COMMIT;


ALTER MATERIALIZED VIEW FORECASTING_REVENUE_CHANGE REFRESH ON DEMAND;
ALTER MATERIALIZED VIEW LOCAL_SUPPLIER_VOLUME REFRESH ON DEMAND;
ALTER MATERIALIZED VIEW PRICING_SUMMARY_REPORT REFRESH ON DEMAND;
ALTER MATERIALIZED VIEW RETURNED_ITEM_REPORTING REFRESH ON DEMAND;
ALTER MATERIALIZED VIEW SHIPPING_MOD_AND_ORDER_PRIO REFRESH ON DEMAND;
ALTER MATERIALIZED VIEW SHIPPING_PRIORITY REFRESH ON DEMAND;


-- refresh mvs --
exec DBMS_MVIEW.REFRESH('FORECASTING_REVENUE_CHANGE', 'F');
exec DBMS_MVIEW.REFRESH('LOCAL_SUPPLIER_VOLUME', 'F');
exec DBMS_MVIEW.REFRESH('PRICING_SUMMARY_REPORT', 'F');
exec DBMS_MVIEW.REFRESH('RETURNED_ITEM_REPORTING', 'F');
exec DBMS_MVIEW.REFRESH('SHIPPING_MOD_AND_ORDER_PRIO', 'F');
exec DBMS_MVIEW.REFRESH('SHIPPING_PRIORITY', 'F');

